language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools 
    - tools # see https://github.com/travis-ci/travis-ci/issues/
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository    
licenses:
    - android-sdk-license-.+
script:
  - ./gradlew build