language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools 
    - tools # see https://github.com/travis-ci/travis-ci/issues/
    - platform-tools
    - build-tools-22.0.1
    - android-23
licenses:
    - android-sdk-license-.+
script:
  - ./gradlew build
